AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    ImageProcessorFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./ImageProcessor/bin/Debug/netcoreapp2.1/publish/
            Handler: ImageProcessor::ImageProcessor.Function::FunctionHandler
            Runtime: dotnetcore2.1
            Timeout: 100
            Policies:
             - AWSLambdaExecute # Managed Policy
             - Version: '2012-10-17' # Policy Document
               Statement:
                 - Effect: Allow
                   Action:
                     - cloudwatch:*
                     - ssm:*
                     - rekognition:*
                     - sagemaker:*
                     - s3:*
                   Resource: '*'
    SessionProcessorFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./SessionProcessor/bin/Debug/netcoreapp2.1/publish/
            Handler: SessionProcessor::SessionProcessor.Function::FunctionHandler
            Runtime: dotnetcore2.1
            Timeout: 100
            Policies:
             - AWSLambdaExecute # Managed Policy
             - Version: '2012-10-17' # Policy Document
               Statement:
                 - Effect: Allow
                   Action:
                     - cloudwatch:*
                     - ssm:*
                     - dynamodb:*
                   Resource: '*'
            Events:
                ProcessSessions:
                  Type: Sc